name: ActionHouse
author: FrostCheat
main: frostcheat\actionhouse\Loader
version: 1.0.0
api: 5.3.0

depend:
  - BedrockEconomy

permissions:
  actionhouse.command:
    default: true
  actionhouse.command.sell:
    default: true
  actionhouse.command.npc:
    default: op
  actionhouse.command.setlanguage:
    default: op